### PR TITLE
Fix ELSE and ELSE IF

### PR DESCRIPTION
**Pull request by corker**
Spotted a problem with ELSE and ELSE IF - next tasks and test cases marked as keywords

### CODE REVIEW

**Comment by bollwyvl** [comment]
Hopefully this is workign well... i'll try it on [binder](https://mybinder.org/v2/gh/corker/jupyterlab_robotmode/fix_else_if?urlpath=lab/tree/tests/mode.test.fixtures/00-tasks.robot) tomorrow!

I wonder if there's a way we could break up the fixture files and let [fast-check](https://github.com/dubzzz/fast-check) re-combine them to give us some more coverage for this kind of stuff. I haven't explored property-based testing much in JS, but seems appropriate here: first it might try fixture ABC, sees that fails, then AB, sees that succeeds, hopefully get to a minimum reproducer that's easy to debug.

**Comment by corker** [comment]
> I wonder if there's a way we could break up the fixture files and let fast-check re-combine them to give us some more coverage for this kind of stuff. I haven't explored property-based testing much in JS, but seems appropriate here: first it might try fixture ABC, sees that fails, then AB, sees that succeeds, hopefully get to a minimum reproducer that's easy to debug.

Don't know if this worth an effort. With the current implementation, it's easy to define robot files and compare them to expected token snapshots. I like that it's easy to open JupyterLab with Bynder and check the highlighting for the robot files visually. Should be enough to build up a good test coverage and easy to pick up I think.

**Comment by martinRenou** [comment]
Tried on binder. It seems to work as intended. Is is ok to merge @bollwyvl ?

**Comment by bollwyvl** [comment]
Yep, binder looks good! :+1:

**Comment by martinRenou** [comment]
Cool. Thanks! I'll make a patch release with this.

**Comment by corker** [comment]
Good stuff, peeps! 💯

**Pull request merged**
