### PR TITLE
Update for JupyterLab 3

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by bollwyvl** [comment]
Are we going to try to support multiple lab versions from a single release?

**Comment by martinRenou** [comment]
idk, do you think it's worth trying? If the lib doesn't change much then people can live with the following I guess:

```
jupyter labextension install @marketsquare/jupyterlab_robotmode@0.1.0
```
If they want it for Lab1 and 2

I am really hoping that the JupyterLab 3 release will get out soon and that extensions will follow the pace so we can drop the old extension system for good.

**Comment by bollwyvl** [comment]
> drop the old extension system for good.

Welp... a lot of folk have invested a lot of effort in existing 2.x stuff. I'm just concerned about adding new features that are Lab 3 only. I guess we can just branch off from the current `master` and backport, if needed.

Also, it's still pretty important to me that this effort results in an easy-to-use robot codemirror mode for consumption _outside_ of jupyter clients... if codemirror had been accepting extensions at the time, I would have gone there first, of course. Practically, I guess this means a simple html page on `gh-pages` that shows it in use, perhaps off unpkg or whatever's easy. Or just a jsfiddle.

Indeed, I _should_ have gotten the simplemode stuff even further upstreamed: all of the simple mode typings are now part of Lab3 itself, as in this [extension-examples PR](https://github.com/jupyterlab/extension-examples/pull/130/files#diff-efbee915f26863aaa6eb2d993fac72859168bb67758f4bb98af4db20ea71e09bR1)... but more typings lead to suffering. Simplemode is kind of a pain, but the concept (not publicly demonstrated) was being able to _simply_ modify the mode dynamically, e.g. say that `Run My Keyword Very Specially` accepts a keyword name as its first argument, and gets highlighted appropriately... did this with a custom display type which modified the states/tokens, akin to [jupyterlab-simple-syntax](https://github.com/deathbeds/jupyterlab-simple-syntax).

**Comment by martinRenou** [comment]
> if codemirror had been accepting extensions at the time, I would have gone there first, of course

Is it something that will change? Hopefully, we could get rid of this package at some point.

**Comment by bollwyvl** [comment]
No, I think the CodeMirror maintainer got tired of the review process, and
that stance is very unlikely to change for cm5. It looks like the cm org
only has a couple core web languages for the cm6, so I'd wager that will be
the shape of things.

We _do_ want to get rid of this, of course... Perhaps the best way would be
to make it indispensable to the core rf project by getting it into an
official browser playground, so that it _has_ to be fixed when new features
are added 😉. I bet rf would "just work" with pyodide.

**Pull request merged**
